In [50]:
from qutip import*
import numpy as np
import matplotlib.pyplot as plt

In [51]:
def f0_t(t, args):
    """ Returns the value of the detuning delta.
        Must receive the value of delta.                """
    return  args["delta"] 

In [52]:
def f1_t(t, args):
    """ Returns the value of the driving function.
        Must receive a sweep rate u.                """
    return  t * args["sweep_rate"] # Linear control (Landau-Zener -> u t) 

In [53]:
steps = 100 #size of the step (precision of simulation)
utau = 0.5 #size of the gap
delta= 1 #detuning
u = 0.01 #sweep rate
tau = utau/u
H0 = sigmaz() #time-independent term, does not include delta
H1 = sigmax() #time-dependent term
t1 = -tau #initial instant
t2 = 0 #final instant

In [54]:
def h_t(t):
    """ Evaluates the Hamiltonian at time t"""
    return f0_t(t,{'delta':delta})*H0+f1_t(t,{'sweep_rate':u})*H1

In [55]:
tlist = np.linspace(t1,t2,steps)

In [56]:
excited_t1 = h_t(t1).eigenstates()[1][1] #excited state at t_1 
excited_t2 = h_t(t2).eigenstates()[1][1] #excited state at t_2

In [57]:
print(h_t(t1).eigenstates())

(array([-1.11803399,  1.11803399]), array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
       Qobj data =
       [[-0.22975292]
        [-0.97324899]]                                              ,
       Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
       Qobj data =
       [[-0.97324899]
        [ 0.22975292]]                                              ],
      dtype=object))


In [58]:
H = [[H0,f0_t],[H1,f1_t]]

Obtaining the state vector

In [60]:

psi0 = excited_t1 #the inital state is the excited state at t_1 
result = sesolve(H,psi0,tlist,args={'sweep_rate':u,'delta':delta})
final_state = result.states[-1] # equivalent to U|psi_0> at the end of the evolution

In [61]:
P = (excited_t2.dag()*final_state)*(final_state.dag()*excited_t2) #Permanence probability excited state
print(P)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.99998213]]
